[bank]
types = ["pay", "move", "receive"]

[[banks.entry]]
type = "receive"
text = "Für Bankzinsen \n erhältst Du \n 180,-"
value = 180

[[banks.entry]]
type = "move"
text = "Geh zum Start \n und hebe \n 200,- ab"
field = "fstart"

[[banks.entry]]
type = "receive"
text = "Die Bank \n bezahlt Dir \n an Zinsen \n 25,-"
value = 25

[[banks.entry]]
type = "pay"
text = "Wegen Überschreitung \n der Fahrordnung \n bezahle \n 15,-"
value = 15

[[banks.entry]]
type = "pay"
text = "Bezahle Deine \n Lebensversicherungs- \n Prämie \n 120,-"
value = 120

[[banks.entry]]
type = "receive"
text = "Für den Verkauf \n von valuepapieren \n erhältst Du \n 50,-"
value = 50

[[banks.entry]]
type = "receive"
text = "An Reisespesen- \n beitrag erhältst Du \n 40,-"
value = 40

[[banks.entry]]
type = "pay"
text = "Für Gehsteigreinigung \n bezahle \n 40,-"
value = 40

[[banks.entry]]
type = "pay"
text = "An die \n Krankenkasse \n bezahle \n 130,-"
value = 130

[[banks.entry]]
type = "move"
text = "Gehe in den \n Arrest"
field = "farrest"

[[banks.entry]]
type = "receive"
text = "Für eine \n Geschäftsvermittlung \n erhältst Du \n 20,- \n Provision"
value = 20

[[banks.entry]]
type = "receive"
text = "In der \n Klassenlotterie \n hast Du \n 20,- \n gewonnen"
value = 20


[[banks.entry]]
type = "receive"
text = "An Umsatzsteuer- \n Rückvergütungen \n erhältst DU \n 35,-"
value = 35

[[banks.entry]]
type = "pay"
text = "Kauf Dir ein Los \n der Klassenlotterie \n und bezahle \n 48,-"
value = 48

[[banks.entry]]
type = "receive"
text = "Für eine \n gewonnene Wette \n erhälst Du \n 120,-"
value = 120