[chance]
types = ["pay","house-repair","land-tax","move","receive","hold"]

[[chances.entry]]
type = "pay"
text = "Die Bank zahlt \n Dir \n an Dividenden \n 60,-"
value = 60

[[chances.entry]]
type = "pay"
text = "Für \n Autoreperatur \n zahle \n 140,-"
value = 140

[[chances.entry]]
type = "pay"
text = "Für unerlaubter \n Parken \n bezahlst Du \n 10,-"
value = 10

[[chances.entry]]
type = "receive"
text = "Für den Bau \n erhälsts Du \n 140,- \n Bundeszuschuß"
value = 140

[[chances.entry]]
type = "move"
text = "Gehe auf Feld 22 \n Passierst Du den \n Start erhältst Du \n 200,-"
field = "f22"

[[chances.entry]]
type = "pay"
text = "Für \n Unfallversicherungen \n bezahlst Du \n 20,-"
value = 20

[[chances.entry]]
type = "house-repair"
text = "Für jedes haus in \n Deinem Besitz bezahlst \n Du an Reperaturkosten \n 20,- \n für jedes Hotel \n 80,-"
house = 20
hotel = 80

[[chances.entry]]
type = "hold"
text = "Diese Karte befreit \n Dich aus dem Arrest ! \n ------------ \n Hebe diese Karte \n auf Du wirst sie \n brauchen"
action = "befreie-arrest"

[[chances.entry]]
type = "land-tax"
text = "An Grundsteuer \n zahlst Du für deine \n Grundstücke \n 10% vom Kaufwert"
value = 10

[[chances.entry]]
type = "move"
text = "Gehe in den \n Arrest"
field = "farrest"

[[chances.entry]]
type = "move"
text = "Gehe zurück um \n 4 Felder"
field = "f-4"

[[chances.entry]]
type = "pay"
text = "Zahle \n 5,- \n Polizeistrafe"
value = 5

[[chances.entry]]
type = "move"
text = "Besuche Graz und \n gehe in der \n Annenstraße spazieren. \n Passierst Du den \n Start erhälst du \n 200,-"
field = "s1002"

[[chances.entry]]
type = "move"
text = "Besuche Salzburg \n und gehe auf dem \n Mirabellplatz spazieren. \n Passierst Du den \n Start erhälst du \n 200,-"
field = "s1012"

[[chances.entry]]
type = "move"
text = "Fahre mit dem \n Flugzeug \n Wien - Venedig \n Passierst Du den \n Start erhälst du \n 200,-"
field = "s3002"