[special]
start = 5
multiplier = 2
text = "Wer auf dieses Feld zu stehen kommt, \n hat Dir die %d fache, besitzt Du auch \n das Feld %d (%s) oder das Feld \n %d (%s), die \n %d fache, hast Du beide Felder %d \n und %d, die %d fache gewürfelte \n Punktezahl zu bezahlen."

[[specials.entry]]
name = "Elektrisches Kraftwerk"
price = 160
price_name = "Preis des Kraftwerkes"

[[specials.entry]]
name = "Seilbahn"
price = 160
price_name = "Preis der Seilbahn"

[[specials.entry]]
name = "Wien - Venedig"
price = 160
price_name = "Preis der Fluglinie"