[andere]
[[andere.entry]]
name = "start"
[[andere.entry]]
name = "chance"
[[andere.entry]]
name = "sparkassa"
[[andere.entry]]
name = "gesetzesverletzung"
[[andere.entry]]
prozent = 10
maximal = 350
name = "vermögendsabgabe"
[[andere.entry]]
name = "gefängnis"
[[andere.entry]]
name = "erwerbssteuer"