[sparkassa]
typen = ["zahle", "gehe", "erhalte"]

[[sparkassa.entry]]
typ = "erhalte"
text = "Für Bankzinsen \n erhältst Du \n 180,-"
wert = 180

[[sparkassa.entry]]
typ = "gehe"
text = "Geh zum Start \n und hebe \n 200,- ab"
feld = "fstart"

[[sparkassa.entry]]
typ = "erhalte"
text = "Die Bank \n bezahlt Dir \n an Zinsen \n 25,-"
wert = 25

[[sparkassa.entry]]
typ = "zahle"
text = "Wegen Überschreitung \n der Fahrordnung \n bezahle \n 15,-"
wert = 15

[[sparkassa.entry]]
typ = "zahle"
text = "Bezahle Deine \n Lebensversicherungs- \n Prämie \n 120,-"
wert = 120

[[sparkassa.entry]]
typ = "erhalte"
text = "Für den Verkauf \n von Wertpapieren \n erhältst Du \n 50,-"
wert = 50

[[sparkassa.entry]]
typ = "erhalte"
text = "An Reisespesen- \n beitrag erhältst Du \n 40,-"
wert = 40

[[sparkassa.entry]]
typ = "zahle"
text = "Für Gehsteigreinigung \n bezahle \n 40,-"
wert = 40

[[sparkassa.entry]]
typ = "zahle"
text = "An die \n Krankenkasse \n bezahle \n 130,-"
wert = 130

[[sparkassa.entry]]
typ = "gehe"
text = "Gehe in den \n Arrest"
feld = "farrest"

[[sparkassa.entry]]
typ = "erhalte"
text = "Für eine \n Geschäftsvermittlung \n erhältst Du \n 20,- \n Provision"
wert = 20

[[sparkassa.entry]]
typ = "erhalte"
text = "In der \n Klassenlotterie \n hast Du \n 20,- \n gewonnen"
wert = 20


[[sparkassa.entry]]
typ = "erhalte"
text = "An Umsatzsteuer- \n Rückvergütungen \n erhältst DU \n 35,-"
wert = 35

[[sparkassa.entry]]
typ = "zahle"
text = "Kauf Dir ein Los \n der Klassenlotterie \n und bezahle \n 48,-"
wert = 48

[[sparkassa.entry]]
typ = "erhalte"
text = "Für eine \n gewonnene Wette \n erhälst Du \n 120,-"
wert = 120