[strassen]
[[strassen.entry]]
stadt = "Bregenz"
name = "Amtsplatz"
miete = [20, 100, 300, 600, 750, 950]
preis = 220
preis_haus = 160
preis_hotel = 160

[[strassen.entry]]
stadt = "Graz"
name = "Murplatz"
miete = [30, 150, 450, 850, 1060, 1200]
preis = 300
preis_haus = 200
preis_hotel = 200

[[strassen.entry]]
stadt = "Graz"
name = "Annenstraße"
miete = [24, 110, 330, 700, 900, 1050]
preis = 250
preis_haus = 150
preis_hotel = 150

[[strassen.entry]]
stadt = "Graz"
name = "Joasneumring"
miete = [20, 100, 300, 600, 750, 950]
preis = 220
preis_haus = 130
preis_hotel = 130

[[strassen.entry]]
stadt = "Eisenstadt"
name = "Jos. Haydngasse"
miete = [6, 30,90, 260, 380, 550]
preis = 100
preis_haus = 50
preis_hotel = 50

[[strassen.entry]]
stadt = "Eisenstadt"
name = "Schloßgrund"
miete = [20, 100,300, 600, 750, 950]
preis = 220
preis_haus = 160
preis_hotel = 160

[[strassen.entry]]
stadt = "Wien"
name = "Kärntnerstraße"
miete = [50, 200,600, 1300, 1600, 1950]
preis = 380
preis_haus = 220
preis_hotel = 220

[[strassen.entry]]
stadt = "Wien"
name = "Mariahilferstraße"
miete = [40, 170,500,1000,1300,1600]
preis = 350
preis_haus = 220
preis_hotel = 220

[[strassen.entry]]
stadt = "Wien"
name = "Kobenzlestraße"
miete = [24,110,330,700,900,1050]
preis = 250
preis_haus = 150
preis_hotel = 140

[[strassen.entry]]
stadt = "Linz"
name = "Landstraße"
miete = [14,70,210,500,700,850]
preis = 180
preis_haus = 100
preis_hotel = 100

[[strassen.entry]]
stadt = "Linz"
name = "Stifterstraße"
miete = [20,100,300,600,750,950]
preis = 220
preis_haus = 160
preis_hotel = 160

[[strassen.entry]]
stadt = "Linz"
name = "Museumstraße"
miete = [22,100,320,780,90,1100]
preis = 250
preis_haus = 150
preis_hotel = 150

[[strassen.entry]]
stadt = "Salzburg"
name = "Mirabellplatz"
miete = [24,110,330,700,900,1050]
preis = 250
preis_haus = 150
preis_hotel = 140

[[strassen.entry]]
stadt = "Salzburg"
name = "Westbahnstraße"
miete = [22,100,320,680,850,1000]
preis = 240
preis_haus = 140
preis_hotel = 130

[[strassen.entry]]
stadt = "Salzburg"
name = "Universitätsplatz"
miete = [24,110,330,700,900,1050]
preis = 250
preis_haus = 150
preis_hotel = 140

[[strassen.entry]]
stadt = "Klagenfurt"
name = "Burggasse"
miete = [10,50,150,450,600,730]
preis = 140
preis_haus = 100
preis_hotel = 100

[[strassen.entry]]
stadt = "Klagenfurt"
name = "Villacherstraße"
miete = [16,80,230,550,710,900]
preis = 200
preis_haus = 110
preis_hotel = 110

[[strassen.entry]]
stadt = "Klagenfurt"
name = "Alter Platz"
miete = [18,90,250,600,730,930]
preis = 210
preis_haus = 120
preis_hotel = 150

[[strassen.entry]]
stadt = "Innsbruck"
name = "M.-Theresienstr"
miete = [30,150,450,850,1050,1200]
preis = 300
preis_haus = 200
preis_hotel = 200

[[strassen.entry]]
stadt = "Innsbruck"
name = "Andreas Hoferstr."
miete = [24,110,330,700,900,1050]
preis = 250
preis_haus = 150
preis_hotel = 140

[[strassen.entry]]
stadt = "Innsbruck"
name = "Boznerplatz"
miete = [30,150,450,850,1050,1200]
preis = 300
preis_haus = 200
preis_hotel = 200

[[strassen.entry]]
stadt = "Bregenz"
name = "Arlbergstraße"
miete = [8,40,100,300,450,600]
preis = 120
preis_haus = 50
preis_hotel = 50

[[strassen.entry]]
stadt = "Bregenz"
name = "Rathausstraße"
miete = [14,70,210,500,700,850]
preis = 180
preis_haus = 100
preis_hotel = 100

[colors]
bregenz = "#555861"
innsbruck = "#0a6a8e"
klagenfurt = "#e69d66"
salzburg = "#a99522"
linz = "#4b6e4d"
wien = "#e94955"
eisenstadt = "#946e5a"
graz = "#937554"